---
identify:
  id: id
user_traits:
  registered_at: created_at
  email: email
events:
  $login.failed:
    - status: '401'
      authenticate: true
      method: POST
      path: "/api/login"
    - status: '200'
      method: POST
      path: "/login"
  $login.succeeded:
    - status: '302'
      authenticate: true
      method: POST
      path: "/login"
      user_traits_from_params:
        email: user.email
    - status: '200'
      method: POST
      path: "/api/login"
      user_traits_from_params:
        email: user.email
    deny_url: http://localhost.charlesproxy.com:3000/login?failed_error=1
  $logout.succeeded:
    status: '302'
    method: DELETE
    path: "/logout"
  $profile_update.succeeded:
    authenticate: true
    status: '302'
    method: PUT
    path: "/"
  $profile_update.failed:
    status: '200'
    method: POST
    path: "/"
  $password_reset.requested:
    status: !ruby/regexp /.*/
    method: POST
    path: "/users/password"
    user_traits_from_params:
      email: user.email
  $password_reset.succeeded:
    status: '302'
    method: PUT
    path: "/users/password"
    user_traits_from_params:
      email: user.email
